### ISSUE TITLE
Hope to support proto 2 default value

### ISSUE THREAD

**Issue by seasonxuan** [tatethurston/TwirpScript#158]
in `proto 2`.

```proto
message SomeQuery {
  optional unit32 offset = 1;
  optional uint32 limit = 2 [default = 10];
}
```

I hope the generated code `*.pb.ts`  have default value , seems look like:

```ts
    // ...
    initialize: function (): SomeQuery {
      return {
        offset: 0,
        limit: 10, // hope to be 10, not 0
      };
    },
```
That means, the web client code `SomeQuery.initialize().limit` is 10, not 0.

**Comment by tatethurston** [comment]
Hey @seasonxuan thanks for opening this. I'm not going to support `proto2` in this library. 

Is there a particular reason setting a different value in your application code is undesirable? 

> That means, the web client code SomeQuery.initialize().limit is 10, not 0.

This value is actually going to be `undefined` not `0` because the field is optional -- only non default values have a value generated by `initialize`.

You can do something like

`someQueryMessage.limit ?? 10` or `someQueryMessage.limit ?? QUERY_DEFAULT_LIMIT`.

**Comment by seasonxuan** [comment]
@tatethurston OK, Thank you.
