### ISSUE TITLE
TypeScript imports broken since use of ProtoScript

### ISSUE THREAD

**Issue by zolex** [tatethurston/TwirpScript#202]
since version 0.0.61 when ProtoScript is used by twirpscript to generate typescript code, the imports of the messages from the services are broken:

it outputs .pb.ts files but the import statements are .pb.js

generated files:
<img width="202" alt="image" src="https://user-images.githubusercontent.com/398739/191938218-81387800-f359-42dc-a91f-1c00c8f66de2.png">

import statements before 0.0.61

<img width="238" alt="image" src="https://user-images.githubusercontent.com/398739/191938308-ab5b18a6-8c10-475b-b0dc-3206ab0100e9.png">

import statements since 0.0.61

<img width="264" alt="image" src="https://user-images.githubusercontent.com/398739/191938386-6ba0b1b5-775e-498e-9e27-ef1d2a47715b.png">

**Comment by tatethurston** [comment]
@zolex Thanks for reporting this. This change is intentional, and was made specifically to support the TypeScript compiler. The full extension path is expected — it’s required for ES modules which don’t implicitly assume a js extension like commonjs does. The TypeScripts compiler expects js extensions and not ts extensions because the compiler does not manipulate import paths: https://www.typescriptlang.org/docs/handbook/esm-node.html. The TypeScript team may reevaluate this in 4.9.

I suspect you're using something other than the TypeScript compiler, such as webpack and ts-loader, to compile your TypeScript code? https://github.com/TypeStrong/ts-loader/issues/1383. 

@andrewbeckman ran into this as well and reported it in https://github.com/tatethurston/TwirpScript/issues/192. Given this rough edge, I'm open to reevaluating this.

**Comment by tatethurston** [comment]
This could look like the following:
- Continue to use full import paths for JS. This delivers correct ESM for browser and node runtimes.
- Drop the `.js` extension for TS. Browser builds like webpack accept ESM without the full extension, so this would only prevent users from running TwirpScript server side as ESM (type: "module" in package.json). I suspect this is an acceptable tradeoff until the TS team better aligns with the rest of the JS ecosystem, and I can expose a config option for the current behavior if anyone requests it.

**Comment by zolex** [comment]
That's interesting, thanks for the detailed answer.

**Comment by tatethurston** [comment]
@zolex I've published https://github.com/tatethurston/TwirpScript/releases/tag/v0.0.64 with the changes I mentioned above. This should "just work" for you -- let me know if you encounter any issues.

**Comment by zolex** [comment]
Thanks man, I'll ask our responsible dev on monday to see if it solves the issues.
