### ISSUE TITLE
package.json Commands Broken

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#51]
After checking out and cloning the repo the following commands seem to be broken:

* `examples:check`
* `examples:gen`
* `test:e2e`

Also the examples seem to depend on the current _published_ version of the package as opposed to the current version of the package in the repo which might lead to some bugs going undetected. I'm not an expert at how to link the examples to the package but if they could be linked then we might be able to run the examples as a soft sort of E2E test.

**Comment by tatethurston** [comment]
Hey @arranf these commands actually all depend on the `test:e2e:prepare` command. This npm links local build instead of pulling the published version of the package. There is a good deal of test coverage I'm planning to backfill. I'm not sure that I want to promote these to E2E tests, right now they are a bridge solution for testing gaps, but I would prefer more targeted tests.

**Comment by arranf** [comment]
@tatethurston That makes sense! 
I'll take a stab at running these commands - it might be worth briefly outlining these in the README?

**Comment by tatethurston** [comment]
I created `examples:setup` and `test:e2e:setup` which is hopefully a bit more discoverable, and is also fully automated.
