### ISSUE TITLE
Fails to Generate Compilable TS for RPC with Empty Interfaces

### ISSUE THREAD

**Issue by arranf** [tatethurston/TwirpScript#99]
In #94 I noted this comment

> As a design goal, TwirpScript should always work with the strictest TypeScript compiler settings. That won't hold true for `estlint` / `prettier` -- I think it _probably_ makes sense to omit code generation from those tools.

If you compile with the `noUnusedParameters` flag on and also have a message that's empty (e.g.`message EmptyParams {}`) you'll generate functions like 

```
export const EmptyParams = {
  writeMessage: function (
    msg: EmptyParams, // This line will fail to compile
    writer: BinaryWriter // This line will fail to compile
  ): void {},

  encode: function (emptyParams: EmptyParams): Uint8Array {
    const writer = new BinaryWriter();
    CheckHealthParams.writeMessage(emptyParams, writer);
    return writer.getResultBuffer();
  },

  readMessage: function (
    msg: Partial<EmptyParams>, // This line will fail to compile
    reader: BinaryReader
  ): void {
    while (reader.nextField()) {
      const field = reader.getFieldNumber();
      switch (field) {
        default: {
          reader.skipField();
          break;
        }
      }
    }
  },
```

The three lines I've commented will fail due to the parameters being unused. An ideal solution would be to prefix these parameters with `_`.

**Comment by arranf** [comment]
Looks like this was a bigger problem on an older version of TwirpScript - on the latest only the `msg` parameter of `writeMessage` (since renamed `_writeMessage`) appears to be a problem.

**Comment by tatethurston** [comment]
Hey @arranf, thanks for opening this. I've been thinking about empty messages -- particularly RPC call sites and whether to special case empty messages so that argument doesn't have to be provided. Eg:

`await SomeRpc({})` vs `await SomeRpc()`.

For the types / serializers, I think it makes sense to special case the empty message case in the compiler and emit less code -- dropping both of the "private" serialization methods "_writeMessage" and "_readMessage".

On a related note, this is a good use case for `Empty` https://developers.google.com/protocol-buffers/docs/reference/google.protobuf#google.protobuf.Empty.

```proto
syntax = "proto3";
import "google/protobuf/empty.proto";

service Foo {
  rpc Bar (google.protobuf.Empty) returns (google.protobuf.Empty);
}
```
